# Generated by Django 3.2 on 2023-04-11 06:27

import apps.base.helper
import django.core.validators
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Category',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=255, verbose_name='Заголовок')),
                ('cat_image', models.ImageField(help_text='Пожалуйста используйте формат JPEG или JPG', upload_to=apps.base.helper.category_img_path, validators=[django.core.validators.FileExtensionValidator(allowed_extensions=['jpg', 'jpeg']), apps.base.helper.validate_size_image], verbose_name='Изображение')),
            ],
            options={
                'verbose_name': 'Категория',
                'verbose_name_plural': 'Категории',
            },
        ),
        migrations.CreateModel(
            name='Store',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=250, verbose_name='Название')),
                ('logo', models.ImageField(help_text='Пожалуйста используйте формат PNG', upload_to=apps.base.helper.store_img_path, validators=[django.core.validators.FileExtensionValidator(allowed_extensions=['png'])], verbose_name='Логотип')),
                ('phone_number', models.CharField(max_length=17, unique=True, validators=[django.core.validators.RegexValidator(message="Номер телефона должен быть в формате: '+996 xxx xx-xx-xx'", regex='^\\+996 \\d{3} \\d{2}-\\d{2}-\\d{2}$')], verbose_name='Номер телефона')),
                ('city', models.CharField(choices=[('Бишкек', 'Бишкек'), ('Ош', 'Ош')], max_length=30, verbose_name='Город')),
                ('location', models.TextField(help_text='Улица, номер дома/строения/корпуса, этаж, номер офиса/кабинета', verbose_name='Адресс:')),
                ('work_time', models.CharField(help_text='Пример: с 10:00 до 20:00', max_length=250, verbose_name='Время работы:')),
                ('value', models.PositiveIntegerField(default=0, verbose_name='Скидка')),
                ('description', models.TextField(verbose_name='Описание')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='Дата создания')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='Дата обновления')),
                ('whatsapp_link', models.URLField(blank=True, null=True, verbose_name='WhatsApp')),
                ('telegram_link', models.URLField(blank=True, null=True, verbose_name='Telegram')),
                ('vk_link', models.URLField(blank=True, null=True, verbose_name='WhatsApp')),
                ('category', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='stores', to='shops.category', verbose_name='Категория')),
            ],
            options={
                'verbose_name': 'Магазин/Организация',
                'verbose_name_plural': 'Магазины/Организации',
            },
        ),
    ]
