# Generated by Django 3.2 on 2023-04-13 06:02

import apps.base.helper
import django.core.validators
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('shops', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='store',
            name='vk_link',
            field=models.URLField(blank=True, null=True, verbose_name='VK'),
        ),
        migrations.CreateModel(
            name='Topical',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=255, verbose_name='Заголовок')),
                ('value', models.PositiveIntegerField(default=0, verbose_name='Скидка')),
                ('topical_img', models.ImageField(help_text='Пожалуйста используйте формат JPEG или JPG', upload_to=apps.base.helper.topical_img_path, validators=[django.core.validators.FileExtensionValidator(allowed_extensions=['jpg', 'jpeg']), apps.base.helper.validate_size_image], verbose_name='Изображение актуальное')),
                ('begin', models.DateField(verbose_name='Начало:')),
                ('end', models.DateField(verbose_name='Конец:')),
                ('published', models.DateField(verbose_name='Дата публикации')),
                ('sub_title', models.CharField(max_length=255, verbose_name='Подзагаловок')),
                ('description', models.TextField(verbose_name='Описание')),
                ('store', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='topicals', to='shops.store', verbose_name='Магазин/Организация')),
            ],
            options={
                'verbose_name': 'Актуальное',
                'verbose_name_plural': 'Актуальные',
            },
        ),
        migrations.CreateModel(
            name='Promotion',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=255, verbose_name='Заголовок')),
                ('promotion_img', models.ImageField(help_text='Пожалуйста используйте формат JPEG или JPG', upload_to=apps.base.helper.promotion_img_path, validators=[django.core.validators.FileExtensionValidator(allowed_extensions=['jpg', 'jpeg']), apps.base.helper.validate_size_image], verbose_name='Изображение акции')),
                ('published', models.DateField(verbose_name='Дата публикации')),
                ('begin', models.DateField(verbose_name='Начало:')),
                ('end', models.DateField(verbose_name='Конец:')),
                ('sub_title', models.CharField(max_length=255, verbose_name='Подзагаловок')),
                ('description', models.TextField(verbose_name='Описание')),
                ('store', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='promotions', to='shops.store', verbose_name='Акция')),
            ],
            options={
                'verbose_name': 'Акция',
                'verbose_name_plural': 'Акции',
            },
        ),
    ]
