# Generated by Django 3.2 on 2023-04-13 07:59

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('shops', '0002_auto_20230413_1202'),
    ]

    operations = [
        migrations.AlterField(
            model_name='promotion',
            name='begin',
            field=models.DateField(blank=True, null=True, verbose_name='Начало:'),
        ),
        migrations.AlterField(
            model_name='promotion',
            name='end',
            field=models.DateField(blank=True, null=True, verbose_name='Конец:'),
        ),
        migrations.AlterField(
            model_name='store',
            name='location',
            field=models.TextField(help_text='Улица, номер дома/строения/корпуса, этаж, номер офиса/кабинета', verbose_name='Адрес:'),
        ),
        migrations.AlterField(
            model_name='topical',
            name='begin',
            field=models.DateField(blank=True, null=True, verbose_name='Начало:'),
        ),
        migrations.AlterField(
            model_name='topical',
            name='end',
            field=models.DateField(blank=True, null=True, verbose_name='Конец:'),
        ),
    ]
