# Generated by Django 3.2 on 2023-04-03 06:22

import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0004_alter_user_reset_password_code'),
    ]

    operations = [
        migrations.AlterField(
            model_name='user',
            name='phone_number',
            field=models.CharField(max_length=17, unique=True, validators=[django.core.validators.RegexValidator(message="Номер телефона должен быть в формате: '+996 xxx xx-xx-xx'", regex='^\\+996 \\d{3} \\d{2}-\\d{2}-\\d{2}$')], verbose_name='Номер телефона'),
        ),
    ]
