# Generated by Django 3.2 on 2023-04-06 05:07

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0006_alter_user_email'),
    ]

    operations = [
        migrations.AlterField(
            model_name='user',
            name='reset_password_code',
            field=models.IntegerField(blank=True, null=True, verbose_name='Koд для сброса пароля'),
        ),
    ]
